### PR TITLE
(Mobile) UI improvements

### LINKED ISSUE #647: UI error handling
UI crashes if response is error 500 or other errors

### PR DESCRIPTION
**Pull request by traines-source**
Some improvements for the UI, without changing too much (see https://github.com/public-transport/transitous/issues/789). This is not perfect yet, consider it a WIP.
* many small CSS, some JS tweaks
* some backports from [prima-mobile](https://github.com/motis-project/prima-mobile)
* improve error handling, resolves #647 
* add URL state management for stops and trips (while I think one could have used [SvelteKit Routing](https://svelte.dev/docs/kit/routing), I've opted for `pushState` like in prima-mobile, which means less refactoring and easier web server configuration)

TODO:
* annoying bug in the AdressTypeahead Combobox on mobile, where if you select an entry, you accidentally click other buttons (Arrival/Departure/Wheelchair beneath...) Didn't yet manage to fix that...
* showing map only on demand on mobile
* URL state mgmt for the itineraries (could be very useful, but also very confusing if returned itineraries change, because we do not have connection ids)

### CODE REVIEW

**Comment by felixguendling** [comment]
We can also merge UI changes step by step in multiple PRs :)
Makes it easier to understand what's going on.

**Comment by traines-source** [comment]
Then have a look :) I might also squash some commits, then you can merge without squashing everything to keep a better/more detailed history.

File: ui/src/lib/ErrorMessage.svelte [hunk 1]
```diff
@@ -0,0 +1,9 @@
+<script lang="ts">
+	let {
+		e
+	}: {
+		e: unknown;
+	} = $props();
+</script>
+
+<div class="m-4 text-red-600"><div class="min-w-0">{e}</div></div>
```
Comment (felixguendling) [inline ui/src/lib/ErrorMessage.svelte:9]:
```suggestion
<div class="m-4 text-destructive"><div class="min-w-0">{e}</div></div>
```

or maybe introduce a error theme dependent error color?

**Review by felixguendling — APPROVED** [review]

**Comment by felixguendling** [comment]
> more detailed history

I would not say it has no benefit but IMO it's not worth the time invest to rebase and squash. This time is better invested in code improvements, new features, bug fixes, etc. :)
